# Generated by Django 5.1.2 on 2024-11-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author_book_genre_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('sci_fi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('biography', 'Biography'), ('mystery', 'Mystery')], max_length=100),
        ),
    ]
